### ISSUE TITLE
Support for multiple root directories

### ISSUE THREAD

**Issue by Jim-Holmstroem** [codewell/data-kale#10]
A common case is to have data on different disks for different tasks.

suggestion:
```toml
[data]
root = '~/data'

[data.aiwizo-project-1]
root = '/big-data'
```
